server:
  port: 4010

spring:
  datasource:
    username: root
    password: luowei...
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://101.43.140.223:3306/openai?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf8&useSSL=false


# 线程池配置
thread:
  pool:
    executor:
      config:
        core-pool-size: 20
        max-pool-size: 50
        keep-alive-time: 5000
        block-queue-size: 5000
        policy: CallerRunsPolicy


# 微信公众号配置
wx:
  config:
    originalId: gh_f24e095424ea
    appid: wx9d16239677b3fd1d
    token: lllwww

# 支付配置；如果你申请了支付渠道，则可以配置 enable = true，否则就配置 false 走流程测试
wxpay:
  config:
    # 状态；true = 开启、false 关闭
    enabled: false
    # 申请支付主体的 appid
    appid:
    # 商户号
    mchid:
    # 回调地址
    notify-url:
    # 商户API私钥路径
    private-key-path: cert/apiclient_key.pem
    # 商户证书序列号：openssl x509 -in apiclient_cert.pem -noout -serial
    merchant-serial-number:
    # 商户APIV3密钥
    api-v3-key:

# 支付配置；如果你申请了支付渠道，则可以配置 enable = true，否则就配置 false 走流程测试
alipay:
  config:
    # 状态；true = 开启、false 关闭
    enabled: true
    app_id: 9021000139618889
    # 回调地址
    notify-url: http://a5pd7p.natappfree.cc/api/sale/ali_pay_notify
    return-url: http://localhost:3000/#/sale
    merchant-private-key: MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQDgCYOw/zwzPuYjkXVySXGvxzzlkKR23CUZd81crcWMh9xpQkXAw8WQmP0bWCF12S6+eYRSzq/jF1KRJoLSvUp3f93Zq+eaT4Ob6GaOhVa+lCETwgfdwSrgvbrFdU0Hc0LGii7qimd0KXTWhmUSEZcTXYoMl/Q9gDu0/LBX9G0OKCHegqsB8Ukj17n1h81E+XPo22tLr2HInNMbAnDpK3WK9oxLz7Tfw+E/TMc5i3gBqZP2PhS0ugIGGO8ckgudPP79uPqVkftUJnxB3GH3shDKNQWscQ9HKZtU8+iOvfgYC6UnESr1TrblD4e1S14dowHK57R0lvne5uMb+VLrUu9dAgMBAAECggEAVwm7POdcBvi3xje7riP0Y/r+oJ06F+ddDnDpusjUB828hrQ1jzc/qPaW1qm9jiBLNbrV+qnL0Wj9LeENUDw0Ewr9MJTFjMC5e7elKFeLJM09sIRgM/nY46kyR4ZT38IavjFvGrWcjZeRicp6t7NXwzFC8bOTMtV/3MeS5wjR2X5peXmbB9jBrhLVxL5UjksgzE86Q2a5t2apMpv3MK31dOb0OKhm7OIjBlh1Bf1NGdOWae/RolVIcFbbL56yY8X87HPNMSwM9NHQ2+Iz8HfZ3NgxUq961jJVoKdUR0qe75DchcwQ6mJJ0BfFRjQ/94IORI4UOtLn5ForuXy0q0C4rQKBgQD/eX9yNwJPzuwZ3IHn5MG4doeh5KLFc3yOs732CLBXUqiATrtzoww1xCglVJiEyym3lMBzQ4BP1K6wyTDbiO64SkgBZ/sfdCDUn5nOekHP4jIO9Qqdb+WRkhZfTcUU5mgM8XjvRiMll41N1jlgd3XAntkeG5zLp/kLxMsClTmVkwKBgQDgf3clbt2f3h7GUcpPOW4lkYQxn0O9I68Od8P0Qm5oXSkveaOjNM3KduUslTkPUG7yVbRU+b9apDSRFx+m4THI1UccDseSdS8saGKcogd9zMsRjafN6f7qISr3nehn3MUvoozk+p4oZjy0dQyj2p8OAhh+RI4WIZez5DjwoId9TwKBgQD4H2WzZU/eeWb/+xVERv4LDTvP9cJNKUwJQPM3WNsEBKjY7R7MQchjE9+12gLDvpoGzfdYO3AMmNENrGnCXq0T2jky/G1+8AfO2i/ExSLUJ6lcs4uauwnpJ0yJRXwrP1hBcel14tXR9e5scaqKUZvQ97aBsmnHtp2AW6KcIJir9wKBgHBLkj+pOzbSlrZBB1+lrJEiPuvLbMjZZqFoCx7NdAjEQOu8frwOl7nkyzIH2qjsZPLXKAMxgiRG6vyAgpapIowBEzbXtcBu2Y/vDxSmf/TPUeyP3RZFK/vVZ3bBCBWb+w6e0rdfHWm76jWiLxZvLwyEw9e1VxV+7DFRwaGrytpFAoGAGg4nmvBmUXuJnCEOEZdHwRhig5mK/5HEj4heTjKq4VLemVG6P3QCav6anLNwea23+PxSKA4vRggRZbm57FYpppjsm/rjOLTQ5uKZ7mgerZ/7pWcm4ByzygPtszvw7tQNZC+vFSybid8HgU+KXhWwIWYUk+ER7NHs0IXKr2VHdvQ=
    alipay-public-key: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAxVks2YEaFkGEsus0jwWNrXkhtiEBlNsf7nig+7p2fHKcL9FRpvxr/TDtiR6t1YNFtBmePMOoWnW/NA1D5UbKjxWMV5hf0y/50fRMxRrVZTQB77GgogB//qJtLRguLJ0SOVAjAB2nBMCz90SNW8TiXK0HOUcpyKDb8ezxEbyY0dcSNuMwWrwzBIkS/RQcDa4rUKfz3KPRvWXOPl6J0gfdhE3/RUEEYf2xUGUC00DtXeu4ffYLi2ChwWs2b3P1uH9qZsfOT8PCmXEgSa3F4pyGVK5t/oEquZLHzoV1hZ6Kvk6ngBUVhnOgNToObIZbNZJVkxIhMNXH0Fv6XBhdPSSsFwIDAQAB
    gateway-url: https://openapi-sandbox.dl.alipaydev.com/gateway.do


app:
  config:
    # 限制接口访问次数
    limit-count: 10
    white-list:

mybatis:
  mapper-locations: classpath:/mybatis/mapper/*.xml
  config-location:  classpath:/mybatis/config/mybatis-config.xml

# 日志
logging:
  level:
    root: info
  config: classpath:logback-spring.xml

# 监控
#management:
#  endpoints:
#    web:
#      exposure:
#        include: "*" # 暴露所有端点，包括自定义端点
#  endpoint:
#    metrics:
#      enabled: true
#    health:
#      show-details: always # 显示详细的健康检查信息
#  metrics:
#    export:
#      prometheus:
#        enabled: true # 启用Prometheus
#  prometheus:
#    enabled: true # 启用Prometheus端点
#  jmx:
#    enabled: true # 启用JMX监控
#  system:
#    cpu:
#      enabled: true # 启用CPU监控
#    memory:
#      enabled: true # 启用内存监控